### ISSUE TITLE
0x52 - Slippage protection for ArrakisV2Router#addLiquidity can be abused if the vault is active in more than one fee tier

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#164]
0x52

medium

# Slippage protection for ArrakisV2Router#addLiquidity can be abused if the vault is active in more than one fee tier

## Summary

When adding liquidity to a vault via the ArrakisV2Router, amounts in and shares received are validated against parameters to ensure that there hasn't been any manipulation of the underlying pools. This is how typical LP is validated but due to the relative nature of a vault share this approach doesn't work.

## Vulnerability Detail

[ArrakisV2Router.sol#L79-L84](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L79-L84)

        require(
            amount0 >= params_.amount0Min &&
                amount1 >= params_.amount1Min &&
                sharesReceived >= params_.amountSharesMin,
            "below min amounts"
        );
        
The checks above are intended to protect against slippage, however they can bypassed as long as the vault is entered into at least 2 different fee tiers. By sandwiching the LP being added in opposite directions across the two pools all the slippage requirements can be met while extracting value from the user.

For simplicity of the math we will assume the following:
    The vault owns all LP in the underlying pool
    LP is deployed over the entire range of the pool
    TokenX = $10 TokenY = $100

Assume the vault already has 100 shares and a user wants 10 shares and to deploy a minimum of 200 TokenX and 20 TokenY

1 - Pool starting values:

    Pool 1
        Token X: 1000
        Token Y: 100
    Pool 2
        Token X: 1000
        Token Y: 100
    
2 - Attacker moves price. The attacker sandwich attacks each pool, pushing it off axis:

    Pool 1
        Token X: 1111.1
        Token Y: 90
    Pool 2
        Token X: 909.1
        Token Y: 110
    Attacker
        Token X: -20.2 (90.9 - 111.1)
        Token Y: 0 (10 - 10)

3 - User adds liquidity. Since the user wants 10 shares they must add they must add 10% (10/100) liquidity

    Pool 1
        Token X: 1222.2
        Token Y: 99
    Pool 2
        Token X: 1000
        Token Y: 121
    User
        Token X: 202 (111.1+90.9)
        Token Y: 20 (9 + 11)

4 - Attacker moves price back.

    Pool 1
        Token X: 1100
        Token Y: 110
    Pool 2
        Token X: 1100
        Token Y: 110
    Attacker
        Token X: 2 (-20.2 + 122.2 - 100)
        Token Y: 0 (11 - 11)

The min max formula is intended to account for changes in the underlying pools with the assumption that if the user is charge more of 1 token they are charged less of the other. Here we can see that by sandwiching the underlying pools this is invalidated and the user is charged more of one token while still paying the full amount of the other. 

## Impact

Slippage protections do not work for vaults with positions in more than one fee tier

## Code Snippet

[ArrakisV2Router.sol#L50-L119](https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L50-L119)

## Tool used

Manual Review

## Recommendation

To prevent this type of attack I would recommend using adding an invariant slippage check, which is the product of the amounts.

        require(
            amount0 >= params_.amount0Min &&
                amount1 >= params_.amount1Min &&
    +           amount1 * amount0 <= params_.amount1Min * params_.amount0Min &&
                sharesReceived >= params_.amountSharesMin,
            "below min amounts"
        );

**Comment by Gevarist** [comment]
Please can you explain me how can we have this attack when we check "sharesReceived >= params_.amountSharesMin"? sharesReceived is computed using amount0Max and amount1Max. So the user want 10% or more for  200 TokenX and 20 TokenY or less.

**Comment by hrishibhat** [comment]
@IAm0x52

**Comment by eliteWalrus4164** [comment]
@Gevarist, agreed that on `ArrakisV2Router::addLiquidity` as stated by this report, the impact can be limited to be arbitrarily small by the `amountSharesMin` parameter

However in my duplicate I show a different scenario on a `SimpleManager::rebalance`, where an operator fails to enforce stricter slippage than the allowed deviation (~1%). I acknowledge that the impact on slippage is limited given the deviation protection though

**Comment by IAm0x52** [comment]
The idea of using the three condition slippage check is to prevent the user from adding liquidity off access because the optimal place is to always add it exactly at market price. This works fine when you have only a single pool. If it is skewed to far towards TokenY then the it won't add enough TokenX which indicates that the liquidity is too far off axis so the transaction should revert. Vice versa is true if it's off axis in the other direction which is why we have to enforce it for TokenY as well. 

The problem is that this approach will no longer hold if there are multiple liquidity pools. Since one pool can be off axis in the tokenX direction while the other can be off axis in the tokenY direction. These skews combine allowing the user to add to two pools that are both heavily skewed off axis (in opposite directions) because both the minimums will be exceeded. This forces the user to pay more assets for the same proportion of liquidity. By checking the product of the minimums you are checking the effective aggregate k of all the underlying pools. When pools are skewed in the same direction this k value won't be affected. However when they are skewed in opposing directions their aggregate k effectively increases. This means by checking the product you are covering the new skew condition introduced by using multiple pools that is otherwise not being checked by the typical LP slippage.

**Comment by IAm0x52** [comment]
> I would totally agree with the reasoning, if not for the sharesReceived >= params_.amountSharesMin which would be triggered if pools in different feeTiers were indeed imbalanced in different directions, since the user would receive less shares (that's the point of the manipulation).

The point is to make the user pay more for the same amount of liquidity

**Comment by eliteWalrus4164** [comment]
> > I would totally agree with the reasoning, if not for the sharesReceived >= params_.amountSharesMin which would be triggered if pools in different feeTiers were indeed imbalanced in different directions, since the user would receive less shares (that's the point of the manipulation).
> 
> The point is to make the user pay more for the same amount of liquidity

The amount the user can pay at most is `params_.amount0Max` and `params_.amount1Max`, so the three parameters `params_.amount0Max`, `params_.amount1Max`, `params_.amountSharesMin` effectively constrain the slippage within a tight range when set properly

This also means that the checks:
```
amount0 >= params_.amount0Min &&
amount1 >= params_.amount1Min
```
are redundant

**Comment by IAm0x52** [comment]
Agreed that you can't make the user pay more than amount1Max or amount2Max. When adding assets if amount0 increases then amount1 should decrease under normal conditions. Here the user can be exploited for both tokens all the way up to amount1Max and amount2Max. Using the product prevents this.

**Comment by eliteWalrus4164** [comment]
> Here the user can be exploited for both tokens all the way up to amount1Max and amount2Max

<s>That's not an exploit, but exactly within the intent of the user, since he is the one setting these parameters</s>

edit: there is indeed a way to have undesired behavior, if the user relaxes one of the amount1Max or amount0Max parameters, but that's more on the user's mistake side. If the user provides parameters amount1Max and amount0Max respecting current arrakis reserves ratio, it would be fine.

I guess it depends on the likelihood of the end-user inputting amount1Max and amount0Max off with regards to ratio.

**Comment by IAm0x52** [comment]
>~~That's not an exploit, but exactly within the intent of the user, since he is the one setting these parameters~~
> 
> edit: there is indeed a way to have undesired behavior, if the user relaxes one of the amount1Max or amount0Max parameters, but that's more on the user's mistake side. If the user provides parameters amount1Max and amount0Max respecting current arrakis reserves ratio, it would be fine.
> 
> I guess it depends on the likelihood of the end-user inputting amount1Max and amount0Max off with regards to ratio.

It's not user input error. The user is not adequately protected from providing off axis liquidity.

**Comment by eliteWalrus4164** [comment]
> It's not user input error. The user is not adequately protected from providing off axis liquidity.

Do you agree that the user can specify inputs (amount0Max, amount1Max, amountSharesMin) which do not allow for `providing off axis liquidity` given current implementation?

**Comment by IAm0x52** [comment]
> Do you agree that the user can specify inputs (amount0Max, amount1Max, amountSharesMin) which do not allow for providing off axis liquidity given current implementation?

Only if liquidity is off axis in the same direction across pools, otherwise they are not adequately protected

**Comment by eliteWalrus4164** [comment]
> Only if liquidity is off axis in the same direction across pools, otherwise they are not adequately protected

Okay if we work the thing backwards:
You are saying that the exploit is about making the user pay up to `amount1Max`, for a given `amount0Max` and `amountSharesMin`;

What happens if the user reduces `amount1Max`?
There is a value `amount1MaxMin`, below which the call will always revert because the ratio:
`mintAmount == (amount1MaxMin*totalSupply)/current1`
goes below `amountSharesMin`
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L368-L383

so if the user calls `addLiquidity` with (`amount0Max`, `amount1MaxMin`, `amountSharesMin`), any smallest deviation caused by frontrunning will revert.

This is equivalent to specifying 0% slippage and adequately protects from `providing off axis liquidity`

**Comment by IAm0x52** [comment]
> > Only if liquidity is off axis in the same direction across pools, otherwise they are not adequately protected
> 
> Okay if we work the thing backwards: You are saying that the exploit is about making the user pay up to `amount1Max`, for a given `amount0Max` and `amountSharesMin`;
> 
> What happens if the user reduces `amount1Max`? There is a value `amount1MaxMin`, below which the call will always revert because the ratio: `mintAmount == (amount1MaxMin*totalSupply)/current1` goes below `amountSharesMin` https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L368-L383
> 
> so if the user calls `addLiquidity` with (`amount0Max`, `amount1MaxMin`, `amountSharesMin`), any smallest deviation caused by frontrunning will revert.
> 
> This is equivalent to specifying 0% slippage and adequately protects from `providing off axis liquidity`

All you've done is identify one of two possible edge cases where it does provide adequate protection (the other being infinite slippage allowance). In all other scenarios it fails to provide adequate protection.

**Comment by eliteWalrus4164** [comment]
> All you've done is identify one of two possible edge cases where it does provide adequate protection (the other being infinite slippage allowance). In all other scenarios it fails to provide adequate protection.

I do not believe it's an edge case and it generalizes:
If you relax the constraint a bit and input (`amount0Max`, `amount1MaxMin*1.01`, `amountSharesMin`), you have roughly 1% slippage accepted, any deviation further than that would revert.

I agree with you it is however not the best UX for the user, and is relying on the front-end to handle these calculations properly

**Comment by kassandraoftroy** [comment]
Yes in my view user has to set amount0Min, amount1Min, amount0Max, amount1Max, amountSharesMin all properly in order to have an unmanipulatable addLiquidity transaction. We understand that this is the case and maybe isn't super desirable UX, but still this issue is invalid in my view. If you set these params propoerly there is simply no way for abuse/manipulation of a depositor no matter how complex the position (across multiple fee tiers etc)

**Comment by hrishibhat** [comment]
Considering this issue a low based on the Sponsor's comment. 
https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/164#issuecomment-1666489043
