### ISSUE TITLE
ast3ros - No slippage protection when adding liquidity to UniswapV3 pool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#84]
ast3ros

medium

# No slippage protection when adding liquidity to UniswapV3 pool

## Summary

In ArrakisV2 vault, when minting Arrakis V2 shares, the underlying assets are deposited to UniswapV3 pool to provide liquidity. However, there is no slippage protection.

## Vulnerability Detail

If the total supply is more than 0, the deposited underlying assets are used to provide liquidity to UniswapV3 pool:

        pool.mint(me, range.lowerTick, range.upperTick, liquidity, "");

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L149

However, there are no parameters for `minDeposit0` and `minDeposit1`, which are used to prevent slippage. The function without slippage protection could be vulnerable to a front-running attack designed to execute the mint call at an unfavorable price.
 
For details of slippage protection when minting, please see:

https://docs.uniswap.org/contracts/v3/guides/providing-liquidity/mint-a-position#calling-mint
https://uniswapv3book.com/docs/milestone_3/slippage-protection/#slippage-protection-in-minting

## Impact

The function is exposed to front-running risk and could mint at a distorted price.

## Code Snippet

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L149

## Tool used

Manual Review

## Recommendation

Estimate the `minDeposit0` and `minDeposit1` like the mint part in the rebalance function. Revert if the total amount of token0 and token1 used is less than the minDeposit0 and minDeposit1.

**Comment by Jeiwan** [comment]
Escalate

This is an invalid finding. As stated by the sponsor, the slippage protection is in place (https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/84#issuecomment-1632875332):
> amountSharesMin of ArrakisV2Router should protect new LPs to get less than what they initially wanted.

@ctf-sec the return of `Pool.mint` doesn't need to be checked because `sharesReceived` is computed exactly how the return of `Pool.mint` would be computed:
1.  `sharesReceived` is returned by `resolver.getMintAmount`:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L493
1. `UnderlyingHelper.computeMintAmounts` is used to compute the amount of shares:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2Resolver.sol#L174
1. `UnderlyingHelper.computeMintAmounts` implements the same logic of computing shares as `Pool.mint` does, and it uses the current pool's state:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L355

Thus, `sharesReceived` is the exact amount of shares that will be minted by `UniswapV3Pool.mint`, and it's correctly checked against the user specified `amountSharesMin`:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L503

Since the report doesn't prove that `UnderlyingHelper.computeMintAmounts` may compute an invalid amount of shares (i.e. different from `UniswapV3Pool.mint`), we cannot say the slippage protection is wrong or is missing.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is an invalid finding. As stated by the sponsor, the slippage protection is in place (https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/84#issuecomment-1632875332):
> > amountSharesMin of ArrakisV2Router should protect new LPs to get less than what they initially wanted.
> 
> @ctf-sec the return of `Pool.mint` doesn't need to be checked because `sharesReceived` is computed exactly how the return of `Pool.mint` would be computed:
> 1.  `sharesReceived` is returned by `resolver.getMintAmount`:
> https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L493
> 1. `UnderlyingHelper.computeMintAmounts` is used to compute the amount of shares:
> https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2Resolver.sol#L174
> 1. `UnderlyingHelper.computeMintAmounts` implements the same logic of computing shares as `Pool.mint` does, and it uses the current pool's state:
> https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L355
> 
> Thus, `sharesReceived` is the exact amount of shares that will be minted by `UniswapV3Pool.mint`, and it's correctly checked against the user specified `amountSharesMin`:
> https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-periphery/contracts/ArrakisV2Router.sol#L503
> 
> Since the report doesn't prove that `UnderlyingHelper.computeMintAmounts` may compute an invalid amount of shares (i.e. different from `UniswapV3Pool.mint`), we cannot say the slippage protection is wrong or is missing.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
I checked all duplicates

Just for taking notes,

aside from #145, which has more math involved and need additional time to verify.

all duplicates just say "mint has unlimited slippage"

Need additional time to validate the claim:

> UnderlyingHelper.computeMintAmounts implements the same logic of computing shares as Pool.mint does, and it uses the current pool's state:
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/libraries/Underlying.sol#L355

If this claim is true, then the issue is not valid because of the amountSharesMin check

**Comment by chainNue** [comment]
From what I understand, the sponsor mention `amountSharesMin` will protect the slippage when adding liquidity via Router, the `ArrakisV2Router:addLiquidity()`. Jeiwan also escalate using a reasoning that it is protected on the router, including `computeMintAmounts` and `sharesReceived` which is exist on the Router.

Most of the duplicates are focusing on the ArrakisV2 `Vault` side on `mint` and `burn` function, for example:
- https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/178

Quoting Jeiwan's [comment](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/33#issuecomment-1636965262) 
> Considering the fact that vaults can be used separately from the router by design, using the router is not enforced.

This issue (and duplicates) didn't mention the `Router` but it's the `ArrakisV2` vault (assuming the vault can be used separately to add liquidity, due to its `external` function, or alternate way when the `Router` is paused) 

Thus the escalation should be rejected and this issue is still valid one.

---

On a side note, this following issue is slippage on Router, which should not valid based on the sponsor & Jeiwan
- https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/157

and I'm not sure why #145 being duplicate of this issue, judge might need to consider to remove it

**Comment by syjcnss** [comment]
This project is using the file structure of Uniswap projects as a reference. The pool/vault contract, which manages underlying assets, is located in a `core` project, while the router contract is situated in a `periphery` project.

I think the security model in uniswap should also be referenced.

The `ArrakisV2` vault in the `core` project is not meant to be directly called by the majority of users who use this protocol to manage LP. This is similar to how Uniswap `v3-core` is not intended to be called by the majority of liquidity providers and traders.

So, the `mint` and `burn` functions in the `ArrakisV2` vault do not need to protect their callers from slippage, similar to the `mint` and `burn` function in the Uniswap `v3-core`, which also does not protect its callers. This should not be a problem.

Users who use the router contract are protected.

Of course, you can argue against me on this, but I believe this is an obvious fact.

**Comment by syjcnss** [comment]
[The doc](https://docs.arrakis.fi/arrakis-v2-core/arrakisv2#mint) supports my above point that `ArrakisV2::mint` is exempt from the requirement of implementing slippage protection.

>Don't call this method naively - it requires additional checks on-chain to be safe from sandwich attacks!

**Comment by kassandraoftroy** [comment]
Thanks @syjcnss for the great explanation of how our codebase is structured and why this is not in fact a valid issues (EOAs/users minting Arrakis tokens should use the peripheral router, only integrating smart contracts that will add these checks themselves at the periphery can safely call the low level mint method)

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Agree with @syjcnss 
https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/84#issuecomment-1666363260
Considering this a low issue based on the above comments. 
https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/84#issuecomment-1666441187

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Jeiwan](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/84/#issuecomment-1636968646): accepted
