### ISSUE TITLE
PRAISE - [DOS] in ArraskisV2.mint(), FullMath.mulDivRoundingUp() used to get the value of amount0 and amount1 may always revert on overflows when it should not

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-arrakis-judging#88]
PRAISE

high

# [DOS] in ArraskisV2.mint(), FullMath.mulDivRoundingUp() used to get the value of amount0 and amount1 may always revert on overflows when it should not

## Summary
FullMath.mulDivRoundingUp() requires overflow behavior may revert  on overflows in ArraskisV2.mint()

## Vulnerability Detail
the protcols fullmath.sol is using solidity ^0.8.4; you'll see that here -- https://github.com/ArrakisFinance/vault-v1-core/blob/7a06f6ffa744eee39b86db9eabb4ea67d3c98aec/contracts/vendor/uniswap/FullMath.sol#L2
and solidity version ^0.8.0 reverts on overflow and underflow by default.

But checking uniswaps version of FullMath.mulDivRoundingUp(), you'll notice that the functions are wrapped in `unchecked` statements because  FullMath relies on the implicit overflow behavior.

Take a look at Uniswap's implementation of FullMath.mulDivRoundingUp()
```solidity
  function mulDivRoundingUp(
        uint256 a,
        uint256 b,
        uint256 denominator
    ) internal pure returns (uint256 result) {
        unchecked {//@audit IT IS WRAPPED IN AN UNCHECKED STATEMENT
            result = mulDiv(a, b, denominator);
            if (mulmod(a, b, denominator) > 0) {
                require(result < type(uint256).max);
                result++;
            }
        }
    }

```
you'll see that here-- https://github.com/Uniswap/v3-core/blob/6562c52e8f75f0c10f9deaf44861847585fc8129/contracts/libraries/FullMath.sol#L115-L127

But Arraskis own isn't wrapped in the unchecked statement 
```solidity
 function mulDivRoundingUp(//@audit MISSING UNCHECKED STATEMENT
        uint256 a,
        uint256 b,
        uint256 denominator
    ) internal pure returns (uint256 result) {
        result = mulDiv(a, b, denominator);
        if (mulmod(a, b, denominator) > 0) {
            require(result < type(uint256).max);
            result++;
        }
    }
```
you'll see that here--https://github.com/ArrakisFinance/vault-v1-core/blob/7a06f6ffa744eee39b86db9eabb4ea67d3c98aec/contracts/vendor/uniswap/FullMath.sol#L118-L128

Now the current implementation of arraskis FullMath.mulDivRoundingUp() may always revert on overflows in  ArraskisV2.mint() when used to get the value of amount0 and amount1 here
```solidity
 amount0 = FullMath.mulDivRoundingUp(
                mintAmount_,
                init0M,
                denominator
            );
```

and here
```solidity
 amount1 = FullMath.mulDivRoundingUp(
                mintAmount_,
                init1M,
                denominator
            );
```

## Impact
 FullMath.mulDivRoundingUp() used to get the value of amount0 and amount1 in ArraskisV2.mint(), may always revert on overflows when it should not 
## Code Snippet
https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L84

https://github.com/sherlock-audit/2023-06-arrakis/blob/main/v2-core/contracts/ArrakisV2.sol#L89
## Tool used

Manual Review

## Recommendation
wrap Arraskis FullMath.mulDivRoundingUp() ln an `unchecked` statement  like Uniswap's own  so that it won't revert on overflows in ArraskisV2.mint() when calculating amount0 and amount1

**Comment by Love4codes** [comment]
Escalate 

FullMath.mulDivRoundingUp() lib needs overflow functionality

Take a look at Uniswap's own [here](https://github.com/Uniswap/v3-core/blob/6562c52e8f75f0c10f9deaf44861847585fc8129/contracts/libraries/FullMath.sol#L115-L127)

Just as described by the watson, "FullMath.mulDivRoundingUp() used to get the value of amount0 and amount1 in ArraskisV2.mint may always revert on overflows when it should not"

**Comment by ctf-sec** [comment]
Brining for sponsor review.

**Comment by syjcnss** [comment]
The `uncheck` in uniswap is just a gas optimization.

In this function, the solidity math overflow check is only apply on this statement,

> result++;

To trigger the overflow, the result has to equal to type(uint256).max. It will revert early on this statement.

> require(result < type(uint256).max);

So the `uncheck` is just to optimize out the unnecessary solidity overflow check on `result++`.

**Comment by Love4codes** [comment]
Boss @syjcnss the Solidity math overflow check is not needed in the .mulDivRoundingUp() function.
That's why uniswap's own has the unchecked keyword. The unchecked keyword in uniswap's own isn't just for gas optimization, it is there to ensure that there won't be reverts due to overflow.

The .mulDivRoundingUp() needs to overflow but it can't because of the missing `unchecked` keyword

**Comment by syjcnss** [comment]
@Love4codes I'm not the boss and not related to Arrakis team. Just find this interesting.

I'm curious about the input parameters that makes the two versions differ. Could you provide an example?

**Comment by Love4codes** [comment]
Hey @syjcnss ,  i found this full math issue during one of my researchs on solodit..
Here are some similar issues related to this one i found 

https://solodit.xyz/issues/m-10-the-fullmath-library-is-unable-to-handle-intermediate-overflows-due-to-overflow-thats-desired-but-never-reached-sherlock-uxd-uxd-protocol-git

https://solodit.xyz/issues/fullmath-requires-overflow-behavior-spearbit-morpho-pdf

https://solodit.xyz/issues/use-unchecked-intickmathsol-andfullmathsol-spearbit-overlay-pdf

As you will see, for the  .mulDivRoundingUp() function to give correct results it needs to allow overflows

**Comment by syjcnss** [comment]
Suggest to demonstrate an input of `(a, b, denominator)` to prove they behave differently.

I cannot view the links you provide. But I found the [uxd protocol report in sherlock](https://github.com/sherlock-audit/2023-01-uxd-judging/issues/273) you linked.
In the uxd protocol, it behaves differently because there's no `unchecked` in the `mulDiv` function. It is a multiplication in side `mulDiv` that makes the difference. Only no `unchecked` in `mulDivRoundingUp` won't cause different behaviors, which is the case in Arrakis.

No unchecked in mulDiv in UXD.
https://github.com/sherlock-audit/2023-01-uxd/blob/main/contracts/libraries/FullMath.sol#L17-L109
```
   function mulDiv(
        uint256 a,
        uint256 b,
        uint256 denominator
    ) internal pure returns (uint256 result) {
        ...

      result = prod0 * inv;         <---- behave differently here
        return result;
    }

```

In Arrakis, mulDiv has unchecked:
https://github.com/ArrakisFinance/vault-v1-core/blob/7a06f6ffa744eee39b86db9eabb4ea67d3c98aec/contracts/vendor/uniswap/FullMath.sol#L19

Besides this, the submission is likely to be invalid in this project. `a`(`mintAmount_`) is set by the user at deposit. `b`(`init0M`) is set by the depolyer and `denominator` is a fixed value `1 ether`. **If the assumption of this report holds true**, `a` **must be a carefully selected value to make revert**. It can be avoided by changing `a`. Because **these two functions are only called at first deposit of the vault**, after the first deposit by any user, there will be no calling to them anymore. There is no fund lose and there is very rare chance of DOS like only one tx revert at first deposit which is intentional caused by one user himself.

**Comment by Love4codes** [comment]
Bro @syjcnss , i still insist that for the .mulDivRoundingUp() function to give correct results it needs to allow overflows

i'd love to hear @IAm0x52 opinion on this

**Comment by Love4codes** [comment]
Bro @syjcnss, i think you're right.

**Comment by hrishibhat** [comment]
@ctf-sec confirming that this issue is a low?

**Comment by ctf-sec** [comment]
> @ctf-sec confirming that this issue is a low?

Agree

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Love4codes](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/88/#issuecomment-1635941187): rejected
